version: "3"

services:
  frontend:
    build:
      context: ./frontend
    environment:
      NODE_ENV: production
    depends_on:
      - backend
      - mysql
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
    environment:
      APP_ENV: production
    depends_on:
      - mysql
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./backend:/app
      - /app/vendor

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kmd123
      MYSQL_DATABASE: blog
      MYSQL_USER: myBoy
      MYSQL_PASSWORD: kmd123
    ports:
      - "0.0.0.0:3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: myBoy # Update this to match your MySQL user
      PMA_PASSWORD: kmd123 # Update this to match your MySQL password
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
    command: ["apache2-foreground"]
